
- name: copy docker-compose file to ec2
  copy:
    src: https://github.com/Noizebomb/webapp-docker-deploy/blob/6011c41071426f0db7ba08261c60380b35a20b03/docker-compose.yml
    dest: ~/
    owner: root
    mode: 664
  with_fileglob:
   - docker-compose.yml

