- name: checkout repo to ec2
  host: web-app-nodes

- name: copy docker-compose file to ec2
  copy:
    src: “{{ docker-compose.yml }}”
    dest: .
    owner: root
    mode: 664
  with_fileglob:
   - docker-compose.yml

- name: install docker-compose

