
- name: copy docker-compose file to ec2
  copy:
    src: "{{ item }}"
    dest: /home/ubuntu/
    owner: ubuntu
    mode: 664
  with_fileglob:
   - files/*

- name: install docker-compose
  apt:
    name: docker-compose
    state: latest
  become: true

- name: run docker-compose
  command: docker-compose up -d
  args:
    chdir: /home/ubuntu/
