name: deploy webapp
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: ssh in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.HOSTNAME }}
            USER_NAME : ${{ secrets.USER_NAME }}
            
        run: |
          mkdir -p ~/.ssh/
          echo "$AWS_PRIVATE_KEY" > ~/.ssh/id_rsa.key
          chmod 600 ~/.ssh/id_rsa.key
          cat >>~/.ssh/config <<END
          Host 52.37.244.139
            HostName $HOSTNAME
            User $USER_NAME
            IdentityFile ~/.ssh/id_rsa.key
            StrictHostKeyChecking no
          END
          
            mkdir web-app-docker
            cd web-app-docker
            git pull git@github.com:Noizebomb/webapp-docker-deploy.git
            docker-compose up -d
