name: deploy webapp
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 52.37.244.139
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"
      