name: deploy webapp
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start AWS EC2
        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - uses: actions/checkout@v2 
      - name: ssh in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.HOSTNAME }}
            USER_NAME : ${{ secrets.USER_NAME }}
            
        run: |
          mkdir -p ~/.ssh/
          echo "$AWS_PRIVATE_KEY" > ~/.ssh/id_rsa.key
          chmod 600 ~/.ssh/id_rsa.key
          cat >>~/.ssh/config <<END
          Host 52.37.244.139
            HostName $HOSTNAME
            User $USER_NAME
            IdentityFile ~/.ssh/id_rsa.key
            StrictHostKeyChecking no
          END
          
            #Now we have got the access of EC2 and we will start the deploy .
            mkdir web-app-docker
            cd web-app-docker
            docker pull noizebomb/springboot-app-2:0.0.1
            docker-compose up -d
